# Generated by Django 4.2.13 on 2024-06-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='in_cart',
            field=models.BooleanField(default=True),
        ),
    ]
